name: flutter_social_media
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.8.0
  get: ^4.6.6
  http: ^1.2.2
  cached_network_image: ^3.2.0
  image_picker: ^0.8.4+4
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Add the assets section here
  assets:
    - assets/images/  # Include the entire images directory
    - assets/icons/